### ISSUE TITLE
Using pipeline to upload artifactories from windows build server

### ISSUE THREAD

**Issue by zmostafa** [jfrog/project-examples#158]
Hello , 
I am not able to upload artifacts from windows to jFrog using declaritve pipeline , I always get this error : 

Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ...
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1036)
		at hudson.FilePath.act(FilePath.java:1025)
		at org.jfrog.hudson.pipeline.declarative.utils.DeclarativePipelineUtils.readBuildDataFile(DeclarativePipelineUtils.java:53)
		at org.jfrog.hudson.pipeline.declarative.utils.DeclarativePipelineUtils.getBuildInfo(DeclarativePipelineUtils.java:118)
		at org.jfrog.hudson.pipeline.declarative.steps.generic.GenericStep$Execution.setGenericParameters(GenericStep.java:85)
		at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.run(UploadStep.java:41)
		at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.run(UploadStep.java:25)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
java.nio.file.InvalidPathException: Illegal char <:> at index 21: rtBuildInfo ci :: develop_385
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at sun.nio.fs.AbstractPath.resolve(Unknown Source)
	at org.jfrog.hudson.pipeline.declarative.utils.ReadBuildDataFileCallable.invoke(ReadBuildDataFileCallable.java:35)
	at org.jfrog.hudson.pipeline.declarative.utils.ReadBuildDataFileCallable.invoke(ReadBuildDataFileCallable.java:19)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2913)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Unknown Source)
Finished: FAILURE

I tried to define the paths to the files in many ways,relative and absloute,with / , // and \\ bust still no success.

**Comment by yahavi** [comment]
@zmostafa,
Thanks for reporting this issue!
It looks similar to this [issue](https://issues.jenkins-ci.org/browse/JENKINS-50132). As suggested there - Can you try to increase Jenkins's allocated memory and CPU?
Please let me know if it helped.

**Comment by zmostafa** [comment]
Hi, Thnkas for your fast reply , I can not update jenkins resources as it is under adminstration from our IT , but I had success uploading the artifacts from a different linux build server,I do not think that is the problem as the error below it state :
 java.nio.file.InvalidPathException: Illegal char <:> at index 21: rtBuildInfo ci :: develop_385

**Comment by yahavi** [comment]
@zmostafa Thanks for the extra information. 
We'll look into it and will notify you of further updates.

**Comment by yahavi** [comment]
@zmostafa version 3.1.0 is released. This version includes the fix for this issue.
We'd appreciate your feedback for that.

**Comment by zmostafa** [comment]
@yahavi Thanks for the fast solution. I will test it and gave you the Feedback, but first can you upload the .hpi for the plugin,you uploaded a zip folder

**Comment by zmostafa** [comment]
@yahavi Thanks I already updated and tested the new Version, It works fine now on Windows , I can upload the artifacts from a Windows build Server using json file. I think we can Close this issue
